INSERT INTO answers (id,text, to_question) VALUES (1,'(2\u00B2)\u207F - 1', 1);
INSERT INTO answers (text, to_question) VALUES ('(k + 1)\u207F + 1', 2);
INSERT INTO answers (text, to_question) VALUES ('անսարքությունների տեղը որոշելու համար', 3);
INSERT INTO answers (text, to_question) VALUES ('փաստի հայտնաբերումը', 4);
INSERT INTO answers (text, to_question) VALUES ('տեղի որոշումը', 5);
INSERT INTO answers (text, to_question) VALUES ('s[j]-ն հեռացվում է', 6);
INSERT INTO answers (text, to_question) VALUES ('\u03c0[i]-ն հեռացվում է', 7);
INSERT INTO answers (text, to_question) VALUES ('1', 8);
INSERT INTO answers (text, to_question) VALUES ('2', 9);
INSERT INTO answers (text, to_question) VALUES ('2', 10);
INSERT INTO answers (text, to_question) VALUES ('2', 11);
INSERT INTO answers (text, to_question) VALUES ('q = p \u036b - 1', 12);
INSERT INTO answers (text, to_question) VALUES ('q = p \u036b + 1', 13);
INSERT INTO answers (text, to_question) VALUES ('չեն համընկնում', 14);
INSERT INTO answers (text, to_question) VALUES ('d = 2', 15);
INSERT INTO answers (text, to_question) VALUES ('d = 2', 16);
INSERT INTO answers (text, to_question) VALUES ('8', 17);
INSERT INTO answers (text, to_question) VALUES ('1', 18);
INSERT INTO answers (text, to_question) VALUES ('89', 19);
INSERT INTO answers (text, to_question) VALUES ('90', 20);
INSERT INTO answers (text, to_question) VALUES ('0', 21);
INSERT INTO answers (text, to_question) VALUES ('2', 22);
INSERT INTO answers (text, to_question) VALUES ('3', 23);
INSERT INTO answers (text, to_question) VALUES ('5', 24);
INSERT INTO answers (text, to_question) VALUES ('6', 25);
INSERT INTO answers (text, to_question) VALUES ('7', 26);
INSERT INTO answers (text, to_question) VALUES ('9', 27);
INSERT INTO answers (text, to_question) VALUES ('C', 28);
INSERT INTO answers (text, to_question) VALUES ('F9', 29);
INSERT INTO answers (text, to_question) VALUES ('EAEC', 30);
INSERT INTO answers (text, to_question) VALUES ('7', 31);
INSERT INTO answers (text, to_question) VALUES ('6E', 32);
INSERT INTO answers (text, to_question) VALUES ('8A1B', 33);
INSERT INTO answers (text, to_question) VALUES ('a-0', 34);
INSERT INTO answers (text, to_question) VALUES ('c-1', 35);
INSERT INTO answers (text, to_question) VALUES ('0 1 0 1  (a b c d)', 36);
INSERT INTO answers (text, to_question) VALUES ('1 0 1 0  (a b c d)', 37);
INSERT INTO answers (text, to_question) VALUES ('0 0 0 1  (a b c d)', 38);
INSERT INTO answers (text, to_question) VALUES ('n - 1', 39);
INSERT INTO answers (text, to_question) VALUES ('1', 40);
INSERT INTO answers (text, to_question) VALUES ('n/2 - 1', 41);
INSERT INTO answers (text, to_question) VALUES ('2', 42);
INSERT INTO answers (text, to_question) VALUES ('1000', 1);
INSERT INTO answers (text, to_question) VALUES ('2000', 1);