INSERT INTO questions(question, rating, topic, answer) VALUES ('Տրամաբանական սխեմայի n տարրերից յուրաքանչյուրը ունի k քանակով անսարքություններ։ Հնարավոր բոլոր անսարքությունների քանակն է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '(k + 1)\u207F + 1');
INSERT INTO questions(question, rating, topic, answer) VALUES ('n մուտքային տարրերով տրամաբանական սխեմայի հնարավոր բոլոր տրամաբանական անսարքքությունների քանակն է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '(2\u00B2)\u207F - 1');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Արատորոշող թեստը նախատեսված է համակարգում ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'անսարքությունների տեղը որոշելու համար');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հսկում է կոչվում ցանկացած տեխնիկական համակարգում կամ սարքում առկա անսարքությունների ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'փաստի հայտնաբերումը');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Արատորոծում է կոչվում ցանկացած տեխնիկական համակարգում կամ սարքում առկա անսարքությունների ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'տեղի որոշումը');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Անսարքությունների աղյուսակի s[i] և s[j] տողերը այնպիսին են, որ  s[j]-ն պարունակում է s[i]-ի նշումները կամ նույն և լրացուցիչ նշումներ։ Այդ դեպքում ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 's[j]-ն հեռացվում է');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Անսարքության աղյուսակի \u03c0[i] և \u03c0[j] աղյուսակները այնպիսին են, որ \u03c0[j]-ն պարունակում է \u03c0[i]-ի նշումները կամ նույն և լրացուցիչ նշումներ։ Այդ դեպքում ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '\u03c0[i]-ն հեռացվում է');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հաջորդական եղանակով մեկբայտանի երկուական կոդի ըստ մոդուլ 3-ի հսկման ձևավորման գումարիչների նվազագույն քանակն է ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '1');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հաջորդական եղանակով մեկբայտանի երկուական կոդի ըստ մոդուլ 5-ի հսկման ձևավորման գումարիչների նվազագույն քանակն է ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '2');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Զուգահեռ եղանակով մեկբայտանի երկուական կոդի ըստ մոդուլ 3-ի հսկման ձևավորման գումարիչների նվազագույն քանակն է ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '2');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Զուգահեռ եղանակով մեկբայտանի երկուական կոդի ըստ մոդուլ 5-ի հսկման ձևավորման գումարիչների նվազագույն քանակն է ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '2');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հսկման մոդուլի նշված դեպքերից ուրում են թվային և թվանշանային հսկումները հավասար ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'q = p \u036b - 1');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հսկման մոդուլի նշված դեպքերից ուրում են թվային և թվանշանային հսկումները հավասար ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'q = p \u036b + 1');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Երկու կոդային բառերի միջև կոդային հեռավորություն է կոչվում կարգերի այն թիվը, որոնցում բառերի նիշերը ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'չեն համընկնում');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Ըստ կենտության հսկման կոդում նվազագույն կոդային հեռավորությունն է ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'd = 2');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Ըստ զույգության հսկման կոդում նվազագույն կոդային հեռավորությունն է ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'd = 2');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Երեք մուտքով "և" տրամաբանական տարրի բոլոր տրամաբանական անսարքությունների քանակն է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '255');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Երեք մուտքով "կամ" տրամաբանական տարրի բոլոր տրամաբանական անսարքությունների քանակն է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '255');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Երեք մուտքով "և-ոչ" տրամաբանական տարրի բոլոր տրամաբանական անսարքությունների քանակն է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '255');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Երեք մուտքով "կամ-ոչ" տրամաբանական տարրի բոլոր տրամաբանական անսարքությունների քանակն է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '255');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Երեք մուտքով "և-ոչ" տրամաբանական տարրի const-0 և const-1 բոլոր հնարավոր անսարքությունների քանակն է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '26');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Երեք մուտքով "կամ-ոչ" տրամաբանական տարրի const-0 և const-1 բոլոր հնարավոր անսարքությունների քանակն է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '25');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Երեք մուտքով "և" տրամաբանական տարրի հսկող խորանարդ է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '011 0');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Երեք մուտքով "կամ" տրամաբանական տարրի հսկող խորանարդ է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '100 1');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Երեք մուտքով "և" տրամաբանական տարրի հսկող d խորանարդ է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '1d1 d');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Երեք մուտքով "կամ" տրամաբանական տարրի հսկող d խորանարդ է՝ ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'd00 d');

INSERT INTO questions(question, rating, topic, answer) VALUES ('Որոշել (45834956)\u2081\u2080 թվի հսկման կոդը ըստ մոդուլ 9-ի։ ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '8');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Որոշել (47837956)\u2081\u2080 թվի հսկման կոդը ըստ մոդուլ 11-ի։ ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '1');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Որոշել (76837256)\u2081\u2080 թվի հսկման կոդը ըստ մոդուլ 99-ի։ ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '89');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Որոշել (25832456)\u2081\u2080 թվի հսկման կոդը ըստ մոդուլ 101-ի։ ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '90');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Որոշել (1011 1101 1011 0111)\u2082 թվի հսկման կոդը ըստ մոդուլ 5-ի։ ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '0');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Որոշել (1011 0110 1101 1110)\u2082  թվի հսկման կոդը ըստ մոդուլ 3-ի։ ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '2');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հեմինգի կոդւվ գրվաշ 101111101001 կոդի որ կարգում է սխալ կատարվել։', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '3');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հեմինգի կոդւվ գրվաշ 101111111101 կոդի որ կարգում է սխալ կատարվել։', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '5');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հեմինգի կոդւվ գրվաշ 101111001101 կոդի որ կարգում է սխալ կատարվել։', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '6');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հեմինգի կոդւվ գրվաշ 101110101101 կոդի որ կարգում է սխալ կատարվել։', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '7');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հեմինգի կոդւվ գրվաշ 101011101101 կոդի որ կարգում է սխալ կատարվել։', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '9');
INSERT INTO questions(question, rating, topic, answer) VALUES ('A9, 7D, BC, 6E բայտերի խմբի համար որն է ընդլայնական հսկման կոդը ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'C');
INSERT INTO questions(question, rating, topic, answer) VALUES ('A9, 7D, BC, 6E բայտերի խմբի համար որն է ընդերկայնական հսկման կոդը ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'F9');
INSERT INTO questions(question, rating, topic, answer) VALUES ('A9, 7D, BC, 6E բայտերի խմբի համար որն է ցիկլիկ հսկման կոդը ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'EAEC');
INSERT INTO questions(question, rating, topic, answer) VALUES ('B6, 5A, C3, BE բայտերի խմբի համար որն է ընդլայնական հսկման կոդը ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '7');
INSERT INTO questions(question, rating, topic, answer) VALUES ('B6, 5A, C3, BE բայտերի խմբի համար որն է ընդերկայնական հսկման կոդը ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '6E');
INSERT INTO questions(question, rating, topic, answer) VALUES ('B6, 5A, C3, BE բայտերի խմբի համար որն է ցիկլիկ հսկման կոդը ', 2, 'ԱՐԱՏՈՐՈՇՈՒՄ', '8A1B');
INSERT INTO questions(question, rating, topic, answer) VALUES ('y = ab\u2081 V ac V b\u2082d արտահայտության համար 1 1 0 0  (a b c d) հավաքածուն նշվածներից որ համար է հսկող ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'a-0');
INSERT INTO questions(question, rating, topic, answer) VALUES ('y = ab\u2081 V ac V b\u2082d արտահայտության համար 1 0 0 0  (a b c d) հավաքածուն նշվածներից որ համար է հսկող ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'c-1');
INSERT INTO questions(question, rating, topic, answer) VALUES ('y = ab\u2081 V ac V b\u2082d արտահայտության համար b\u2082-0 անսարքության հսկող հավաքածուն է ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '0 1 0 1  (a b c d)');
INSERT INTO questions(question, rating, topic, answer) VALUES ('y = a\u0305\u2081b\u0305\u2081c \u02c5 a\u2082d \u02c5 b\u2082d արտահայտության համար d-1 անսարքության հսկող հավաքածուն է ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '1 0 1 0  (a b c d)');
INSERT INTO questions(question, rating, topic, answer) VALUES ('y = a\u0305\u2081b\u0305\u2081c \u02c5 a\u2082d \u02c5 b\u2082d արտահայտության համար b\u2082-1 անսարքության հսկող հավաքածուն է ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '0 0 0 1  (a b c d)');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հաջորդական եղանակով n-կարգանի p \u036b-ական թվի q = p \u036b - 1 մոդուլով հսկման կոդի ձևավորման փուլերի նվազագույն քանակն է ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'n - 1');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հաջորդական եղանակով n-կարգանի p \u036b-ական թվի q = p \u036b - 1 մոդուլով հսկման կոդի ձևավորման գումարիչների նվազագույն քանակն է ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '1');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հաջորդական եղանակով n-կարգանի p \u036b-ական թվի q = p \u036b + 1 մոդուլով հսկման կոդի ձևավորման փուլերի նվազագույն քանակն է ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', 'n/2 - 1');
INSERT INTO questions(question, rating, topic, answer) VALUES ('Հաջորդական եղանակով n-կարգանի p \u036b-ական թվի q = p \u036b + 1 մոդուլով հսկման կոդի ձևավորման գումարիչների նվազագույն քանակն է ', 3, 'ԱՐԱՏՈՐՈՇՈՒՄ', '2');